

#### GET User
GET http://localhost:4004/fun-org/User


#### GET Activity Group
GET http://localhost:4004/fun-org/ActivityGroup


### GET Activity Group and expand
GET http://localhost:4004/fun-org/ActivityGroup?$expand=members


#### GET Member
GET http://localhost:4004/fun-org/Members

