#### GET User
GET http://localhost:4004/fun-org/User


#### GET Activity
GET http://localhost:4004/fun-org/Activity


#### GET Activity Group
GET http://localhost:4004/fun-org/ActivityGroup


### GET Activity Group and expand owner,activity,members
GET http://localhost:4004/fun-org/ActivityGroup?$expand=owner,activity,members


#### GET Member
GET http://localhost:4004/fun-org/Members





#### find Users to join
####    location = Tel Aviv
####    interest = music
GET http://localhost:4004/fun-org/User?$filter=location eq 'Tel Aviv' and interest_ID eq 'music'

#### find Activities to create new ActivityGroup
####    date = September
####    location = Tel Aviv
####    category = music
GET http://localhost:4004/fun-org/Activity?$filter=date eq 2023-09-01 and location eq 'Tel Aviv' and category_ID eq 'food'


#### find Activity Group to join, 
####    date = September 2023
####    location = Walldorf 
####    category = music
GET http://localhost:4004/fun-org/ActivityGroup?$expand=owner,activity&$filter=activity/date eq 2023-09-01 and activity/category_ID eq 'music' 


